### ISSUE TITLE
URL encoding issue in XML dump "amp;"

### ISSUE THREAD

**Issue by jmcmurry** [identifiers-org/registry#1]
https://github.com/identifiers-org/registry/blob/master/prefix/ncit.md is correct, and the identifiers.org web app link is correct, but the corresponding stanza in the xml dump is not, I think due to a URL encoding issue.

```xml
		<namespace>ncit</namespace>
		<documentations>
			<documentation type="PMID">urn:miriam:pubmed:19789731</documentation>
			<documentation type="URL">http://ncit.nci.nih.gov/ncitbrowser/pages/help.jsf</documentation>
		</documentations>
		<resources>
			<resource id="MIR:00100181" state="down" reliability="86">
				<dataResource>http://ncit.nci.nih.gov/</dataResource>
				<dataEntityExample>C80519</dataEntityExample>
				<dataEntry>http://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&amp;code=$id</dataEntry>
				<dataInfo>NCIt at National Cancer Institute</dataInfo>
				<dataInstitution>National Cancer Institute, Center for Bioinformatics, Maryland</dataInstitution>
				<dataLocation>USA</dataLocation>
			</resource>
		</resources>
```
In the xml stanza above, there is an encoding issue in the URL: `amp;` should just be `&`.
Interestingly, the link in the identifiers.org web app works. 
I think the disconnect is longstanding. This might be consistent with the reliability score being 86% (from my 2015 download) and now (63%) according to the latest xml dump, though I'm not sure what the denominator is in terms of time period.

In any event, the XML needs to be remedied, and the disconnect between the app and the XML also needs to be remedied. Thanks.

cc: @putmantime

**Comment by identifiers-org** [comment]
Hi Julie,

Thanks for pointing this out. This XML dump is on the way out. Could you please use the new dump from http://identifiers.org/service/registryxml which has the correct representation.

Cheers,
Sarala
