### ISSUE TITLE
What, no RNAcentral?

### ISSUE THREAD

**Issue by nerdstrike** [identifiers-org/registry#2]
Can't tell if this is used to populate identifiers.org, but I was surprised when I couldn't find RNAcentral. The identifiers are fairly predictable at the moment.

**Comment by identifiers-org** [comment]
Thanks for pointing this out. Could you please complete our prefix request form at https://identifiers.org/request/prefix to assist us with the relevant information.

**Comment by nsjuty** [comment]
isn't it this: http://identifiers.org/rnacentral/
