### ISSUE TITLE
de-double MGI IDs

### ISSUE THREAD

**Issue by cmungall** [identifiers-org/registry#8]
identifiers.org MGI URLs have `:`s in them, which means the URI is encoded as

http://identifiers.org/mgi/MGI%3A5624838

which is not optimal

The whole MGI:MGI thing was a mistake inherited from GO a while ago, over the definition of identifier (local vs prefixes).

Can we have the URI prefix for MGI be http://identifiers.org/mgi/? So URLs would be of the form http://identifiers.org/mgi/5624838

**Comment by jmcmurry** [comment]
Hi Chris, this is already addressed in the new patterns they support.
If you have a context map with `MGI` mapping to `http://identifiers.org/MGI:` it works fine.

**Comment by cmungall** [comment]
OK, so this is a bit confusing

both

  1. http://identifiers.org/MGI:80863
  2. http://identifiers.org/mgi/MGI:80863

are supported (is the plan to make the first canonical and deprecate the 
second?)

1 is preferable as it doesn't double up, but it still includes the ':' 
in the URI, which is problematic due to the need to escape

**Comment by jmcmurry** [comment]
In what context must you escape them? All modern browsers support the ':' natively now.

**Comment by jmcmurry** [comment]
Re: deprecation, there are already URIs in the wild various places; I don't think they plan to (or should) stop resolving them. In time, my understanding is they do plan to update the documentation to the new patterns. Agreed it is confusing mid-stride.

**Comment by sarala** [comment]
Hi Chris and Julie, 

Yes, we are actively promoting (1) prefix:identifier compact identifier form. However, we will continue to support (2) for now.

**Comment by cmungall** [comment]
I'm not really concerned with browser behavior. If identifiers.org URLs are to be used as identifying URIs within a semantic web stack there's a complex set of specifications, to be waded through.

I haven't looked at these for a while, but colons have always been problematic.

For example, if we start at the CURIE spec https://www.w3.org/TR/curie/ 

```
curie       :=   [ [ prefix ] ':' ] reference
prefix      :=   NCName
reference   :=   irelative-ref (as defined in IRI)
```

irelative-ref is defined here:

https://www.ietf.org/rfc/rfc3987.txt

which eventually bottoms out here:

```
isegment-nz-nc = 1*( iunreserved / pct-encoded / sub-delims
                        / "@" )
                  ; non-zero-length segment without any colon ":"
```

":"s used to be very problematic with a lot of toolchains, but it seems now that the specs may not be always adhered to and many stacks will do the 'intended' thing...

...but why risk it? What is the reason for MGI being any different than others?

**Comment by sarala** [comment]
Hi Chris,

At the moment MGI is considered as being part of the identifier which results in:
 1. http://identifiers.org/MGI:80863
 2. http://identifiers.org/mgi/MGI:80863

Technically, it is much simpler to do 
 1. http://identifiers.org/MGI:80863
 2. http://identifiers.org/mgi/80863 (currently not supported)
However, it is still not clear to me whether the data provider would approve this.

**Comment by jmcmurry** [comment]
When last they were asked about this MGI was not ok with http://identifiers.org/mgi/80863. Things may have changed, just thought I'd convey what I know to date.

**Comment by sarala** [comment]
Thanks Julie. I'm not sure how to address these differences in approaches between data providers and tool builders.

**Comment by jmcmurry** [comment]
IMHO, I think you're doing all you can.
